### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by McCodeman** [anuvu/zot#159]
As a community member, I want to understand what the acceptable code of conduct is for participating in this project.

Acceptance Critera:
* [x] Adopt a code of conduct that is compatible with [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md).
* [x] Create and publish Code of Conduct in CODE_OF_CONDUCT.md (or asciidoc) at root of repository.
* [x] Link to CODE_OF_CONDUCT.md (or asciidoc) from README.md

**Comment by rchincha** [comment]
PR #167 addresses this issue
