### ISSUE TITLE
Development Environment Setup Documentation

### ISSUE THREAD

**Issue by McCodeman** [anuvu/zot#160]
As a new contributor, I want instructions on how to setup a best practice development environment to work on and debug the project code and other assets.

Acceptance Criteria:
* [x] Publish Development Environment Setup Instructions by either
  * [ ] Adding a section to CONTRIBUTING.md (or asciidoc)
  * [x] Creating separate document in docs.

**Comment by rchincha** [comment]
https://github.com/anuvu/zot/blob/master/CONTRIBUTING.md
Fixed here ^
