### ISSUE TITLE
Third-Party Dependency and License List

### ISSUE THREAD

**Issue by McCodeman** [anuvu/zot#161]
As a user, I want a list of all the project's direct software dependencies and their respective licenses.

Acceptance Criteria:
* [x] Use a tool to automate collection of direct dependencies and their licenses. For example, the following tools do this:
  * https://github.com/google/go-licenses
  * https://github.com/go-enry/go-license-detector
* [x] Publish list of third-party dependencies and licenses to THIRD-PARTY-LICENSES.md (or asciidoc).

A good example output is https://github.com/kubernetes/cloud-provider-aws/blob/master/THIRD-PARTY-LICENSES.

**Comment by rchincha** [comment]
Fixed as part of https://github.com/anuvu/zot/pull/165
