### ISSUE TITLE
Decide on Markdown or Asciidoc for project documentation.

### ISSUE THREAD

**Issue by McCodeman** [anuvu/zot#164]
As a user, I need a consistent documentation formatting standard.

Acceptance Criteria
* [x] Choose one of:
  * [ ] Asciidoc
  * [x] Markdown

This standard should be used for all documentation including root docs such as README, CONTRIBUTING, etc.

**Comment by rchincha** [comment]
I voted for markdown.

**Comment by rchamarthy** [comment]
Github Flavored Markdown

**Comment by tych0** [comment]
Yes, markdown sounds good to me!

**Comment by rchincha** [comment]
All our documentation is in github markdown with dot-md extensions
