### ISSUE TITLE
SessionLogger includes unhelpful static `caller` 

### ISSUE THREAD

**Issue by mikemccracken** [anuvu/zot#177]
SessionLogger being a nested func means that all the logs include 
`"caller":"/root/go/src/github.com/anuvu/zot/pkg/log/log.go:113"`
and it's always the same. 

If there's a way to reorganize the code to get a useful Caller(), great, otherwise can we leave it out and make the logs a little easier to read?

Thanks!

**Comment by shimish2** [comment]
I will fix this, looks like in case  of info and debug level caller is static while for error level it is printing actual caller.

**Comment by shimish2** [comment]
@mikemccracken I look into this and as per my understanding ```"caller":"/root/go/src/github.com/anuvu/zot/pkg/log/log.go:113"``` is printed everytime we call WriteHeaders but apart from that for me it is printing different caller also ```{"level":"debug","v1path":"github.com/opencontainers/image-spec/specs-go/v1","name":"time::Time","caller":"/root/go/src/github.com/anuvu/zot/pkg/storage/storage.go:82","time":"2021-02-17T23:14:27.347732725Z","message":"detected jump outside permitted packages"}```. Please let me know if I am understanding this issue incorrect.

cc @rchincha

**Comment by mikemccracken** [comment]
Yeah I was looking at logs that were mostly from WriteHeaders

```

**Comment by rchincha** [comment]
Closing this issue.
