### ISSUE TITLE
logs: add an audit log for API calls

### ISSUE THREAD

**Issue by rchincha** [anuvu/zot#178]
Keep a separate audit log to track only API actions (separate from verbose logs)

**Comment by roxanaN** [comment]
Hi, @rchincha!

1. How to configure file path for audit.log?
I propose:

```
audit:
    path: audit.log
```

2. Should we write the messages in both log files?

3. The message format should be identical to the one used in zot.log?
In case of zot.log, the Authorization is replaced with '*'. If username is available, should we include it?
What should we include in case of bearer authentication?

**Comment by rchincha** [comment]
log:
  level: debug
  output: /tmp/zot.log
  **audit: /tmp/zot-audit.log**

**Comment by rchincha** [comment]
The format should be:
subject=username, action=http.Method (PUT,POST,PATCH), object=URI, status=Only if succe
