### ISSUE TITLE
Other storage backends?

### ISSUE THREAD

**Issue by the-maldridge** [anuvu/zot#179]
Right now it looks like Zot is a fantastic registry if I want to run it on a single machine.  I'm particularly drawn to the LDAP support even though my preferred authentication only speaks LDAP by proxy.  What I don't see is a way to run zot horizontally available.  Is there no way to run Zot on top of a remote object store or similar option with nonlocal storage?

**Comment by rchincha** [comment]
@the-maldridge thanks for looking at zot.

As long as remote storage can be locally mounted (eg., [1], [2], [3]), zot can be configured to serve from that mount point. Yes, we don't support ability to manage multiple mount points yet.

About horizontal scaling, from our experience, the network becomes a bottleneck far quicker than CPU and memory and we are thinking about addressing clustering [4] with this in mind.

[1] https://github.com/s3fs-fuse/s3fs-fuse
[2] https://azure.microsoft.com/en-us/services/storage/files/
[3] https://docs.ceph.com/en/latest/man/8/mount.ceph/
[4] https://github.com/anuvu/zot/issues/125

**Comment by the-maldridge** [comment]
Thanks for the speedy reply.  I was most concerned with doing any mountpoints that don't support full POSIX abstraction based on the deduplication via hardlinks, which I don't think work quite right on some of the fuse drivers I use regularly.

I'll keep an eye on #125.

**Comment by rchincha** [comment]
@the-maldridge pls take a look at: https://github.com/anuvu/zot/releases/tag/v1.2.0
It is an interim solution until we have full clustering (although we consider both complementary)

**Comment by the-maldridge** [comment]
I must admit its not super clear what I'm looking at.  Can you post a bit more detail about what changed or where I can find more documentation?

**Comment by rchincha** [comment]
> 
> 
> I must admit its not super clear what I'm looking at. Can you post a bit more detail about what changed or where I can find more documentation?

To summarize: "Serve multiple storage paths (and backends) using a single zot server"

Perhaps best explained with an example config:
https://github.com/anuvu/zot/blob/master/examples/config-multiple.json

Basically, with this release, it is now possible to *store* images in multiple mounts/backends but *serve* them in a unified way.

Hope this makes it clearer.

**Comment by rchincha** [comment]
Just to add:

Your storage can now be one or more of these:
1. Local storage
2. Traditional remote storage such as NFS and CIFS
3. Cloud storage such as [AWS](https://github.com/s3fs-fuse/s3fs-fuse), [Azure](https://github.com/Azure/azure-storage-fuse)

**Comment by rchincha** [comment]
@the-maldridge would love to hear your feedback, if and when you are able to try this feature out.

**Comment by the-maldridge** [comment]
For sure, I've been busy this last week with the Freenode melt-down, but
I should have some time this week to take a look.

**Comment by rchincha** [comment]
We are making some progress with PR #216. Planning to add support for other vendors as well.
The original proposal of using fuse drivers holds valid. PR #216 allows us to avoid fuse drivers altogether which is useful when running in containers without privileges (bind mounting /dev/fuse needs SYS_ADMIN capabilities)
