### ISSUE TITLE
Implement an API for performance monitoring

### ISSUE THREAD

**Issue by andaaron** [anuvu/zot#213]
Design an implement an API which provides information about the performance of the zot server which could be used for debugging.

Let's look at:
- storage - how much space is used per repo (folder)
- storage - how much total space is used
- latency counters - min/max/average - per repo (folder) per specific time interval
- how many times an image was downloaded
- how many times has an image been uploaded to a repo (folder)

We need to also check what docker is offering in this sense.

[Additional items]

Generally we look at following params:

Size of the blob/layer/container with its name and tag details.
Latency between zot service and S3 bucket
Latency between zot service and client
Start time of request
Transaction time of request
Client IP/hostname
Bytes transferred from client
Response status to client with IP address in one line
Errors in case of terminated transaction.
Crash log location if any and one line reason

Apart from the above through prometheus node exporter, we expect to monitor

1. POd CPU utilization
2. POD men utilization
3. Host CPU and Mem
4. Pod evictions and their reasons
5. Container run time storage disk pressure
6. Host availability

Alerts will be set on all above observability params apart from S3 bucket storage utilization in AWS Will let you know, if I can think of more

**Comment by rchincha** [comment]
https://prometheus.io/docs/concepts/metric_types/

**Comment by adodon2go** [comment]
For zot minimal, we can have a in-memory counter set for metrics and under extended, prometheus is fine

**Comment by adodon2go** [comment]
We have two cases: 
   a) for zot extended a Prometheus client library is used (+1MB overhead on the zot binary size)
   b) for zot minimal metrics are cached in-memory and a node-exporter was written for the middleware transformation from raw JSON format (zot) -> Prometheus types.
      There is no binary overhead by adding instrumentation in this way.
      Currently the code for node exporter is here: https://github.com/adodon2go/nodeexporter
      The plan is to integrate it inside anuvu/zot (having an extra Makefile target for its build).
      Ideally we should add it here after its maturity: https://github.com/prometheus/prometheus/wiki/Default-port-allocations
      
The types of events we are currently monitoring: 
   1. HttpConnRequests - counter - number of HTTP connection requests that was handled by zot server (that can be aggregated by http "method" and return "code" labels)
      From this metric we can figure out requests rate (in what period of time the server was really busy) and errors rate.
      We can then take a look at another metric : average request latency to see how the server behaved during that period of time
   2. HttpServeLatency - summary - latency of serving http requests (that can be aggregated by image "repo" label)
      From this we can figure out the average latency, minimum and maximum latency.
      Also what present interest in this area is finding 95 percentile of the requests latency per repo (what is the latency in 95% of all requests made?)
   3. StorageUsage - gauge - how much space each repo is using
   4. UploadCounter & Download Counter - total number times an image was uploaded/downloaded (aggregated by repo)
   5  ZotGeneralInfo - contains general information about zot - binary type (minimal/extended), what go version was used to compile the binary, commit number, etc
   
Other metrics maybe useful like finding out how much memory is zot using, number of goroutines in the system, etc (this should come for free using prometheus client library)

**Comment by rchincha** [comment]
Histogram for what type of HTTP APIs called (GET, PUT, PATCH, etc) so we can tell what type of workload it is - read-heavy, write-heavy, mixed, etc

**Comment by hkrpavan** [comment]
Here is the log information expecting from SRE point of view:

Size of the blob/layer/container with its name and tag details.
Latency between zot service and S3 bucket
Latency between zot service and client
Start time of request
Transaction time of request
Client IP/hostname
Bytes transferred from client
Response status to client with IP address in one line
Errors in case of terminated transaction.
Crash log location if any and one line reason

Apart from the above through prometheus node exporter, we expect to monitor

1. POd CPU utilization
2. POD men utilization
3. Host CPU and Mem
4. Pod evictions and their reasons
5. Container run time storage disk pressure
6. Host availability

Alerts will be set on all above observability params apart from S3 bucket storage utilization in AWS Will let you know, if I can think of more
