### ISSUE TITLE
add token-based authentication

### ISSUE THREAD

**Issue by rchincha** [anuvu/zot#24]
Currently, supports only "BASIC", need "BEARER token" support as well.
Also, so we don't clobber LDAP server if configured as authN backend.

**Comment by jdolitsky** [comment]
Hi - I've put together this Go library which helps with validating docker-style JWT tokens retrived from an auth service: https://github.com/chartmuseum/auth#authorizing-an-incoming-request-example

**Comment by rchincha** [comment]
@jdolitsky thanks for the pointer. We should be able to use this although for the first cut intial authN will be based off of BASIC and LDAP.
